import type { WidgetRegistryItem } from "../contracts/widgetRegistry.types";

export const widgetRegistry = {
  metrics_snapshot: {
    kind: "metrics_snapshot",
    label: "Metrics Snapshot",
    description: "Core KPI performance signals for the selected org.",
    category: "performance",
    allowedRoles: ["COMPANY_MANAGER", "ITG_SUPERVISOR", "DIRECTOR"],
    defaultSize: "wide",
    allowedSizes: ["medium", "wide"],
    configurable: true,
  },
  workforce_snapshot: {
    kind: "workforce_snapshot",
    label: "Workforce Snapshot",
    description: "People, coverage, and readiness signals.",
    category: "workforce",
    allowedRoles: ["COMPANY_MANAGER", "ITG_SUPERVISOR", "DIRECTOR"],
    defaultSize: "wide",
    allowedSizes: ["medium", "wide"],
    configurable: true,
  },
  route_lock_snapshot: {
    kind: "route_lock_snapshot",
    label: "Route Lock",
    description: "Schedule, quota, and route-lock operating signals.",
    category: "operations",
    allowedRoles: ["COMPANY_MANAGER", "ITG_SUPERVISOR", "DIRECTOR"],
    defaultSize: "medium",
    allowedSizes: ["medium", "wide"],
    configurable: true,
  },
  dispatch_snapshot: {
    kind: "dispatch_snapshot",
    label: "Dispatch Signal",
    description: "Today’s dispatch events and capacity signals.",
    category: "operations",
    allowedRoles: ["COMPANY_MANAGER", "ITG_SUPERVISOR", "DIRECTOR"],
    defaultSize: "medium",
    allowedSizes: ["medium", "wide", "rail_half", "rail_full"],
    configurable: true,
  },
  quick_actions: {
    kind: "quick_actions",
    label: "Quick Actions",
    description: "Shortcut links. Kept for legacy layouts only.",
    category: "navigation",
    allowedRoles: ["COMPANY_MANAGER", "ITG_SUPERVISOR"],
    defaultSize: "medium",
    allowedSizes: ["small", "medium"],
    configurable: false,
  },
  activity_feed: {
    kind: "activity_feed",
    label: "Activity Feed",
    description: "Recent operational notes and system signals.",
    category: "activity",
    allowedRoles: ["COMPANY_MANAGER", "ITG_SUPERVISOR", "DIRECTOR"],
    defaultSize: "rail_half",
    allowedSizes: ["wide", "rail_half", "rail_full"],
    configurable: true,
  },
} satisfies Record<string, WidgetRegistryItem>;
