// path: apps/web/src/shared/navigation/registry.ts

import type { NavigationItemDefinition } from "./types";

export const NAVIGATION_REGISTRY: NavigationItemDefinition[] = [
  {
    key: "home",
    label: "Home",
    href: "/home",
    icon: "home",
    visibility: "default",
    defaultRoles: ["APP_OWNER", "ADMIN", "COMPANY_MANAGER", "ITG_SUPERVISOR"],
    sortOrder: 10,
  },

  {
    key: "director_executive",
    label: "Executive",
    href: "/director/executive",
    icon: "chart",
    visibility: "default",
    defaultRoles: ["DIRECTOR"],
    sortOrder: 20,
  },
  {
    key: "director_workforce",
    label: "Workforce",
    href: "/director/workforce",
    icon: "workforce",
    visibility: "default",
    defaultRoles: ["DIRECTOR"],
    exposeWhenPermissions: ["workforce_access"],
    sortOrder: 30,
  },

  {
    key: "director_people",
    label: "People",
    href: "/director/people",
    icon: "people",
    visibility: "default",
    defaultRoles: ["DIRECTOR"],
    exposeWhenPermissions: ["people_access"],
    sortOrder: 35,
  },

  {
    key: "bp_owner_overview",
    label: "Overview",
    href: "/bp-owner",
    icon: "home",
    visibility: "default",
    defaultRoles: ["BP_OWNER"],
    exposeWhenPermissions: ["bp_owner_access"],
    sortOrder: 40,
  },
  {
    key: "bp_owner_workforce",
    label: "Workforce",
    href: "/bp-owner/workforce",
    icon: "workforce",
    visibility: "default",
    defaultRoles: ["BP_OWNER"],
    exposeWhenPermissions: ["bp_owner_access", "workforce_access"],
    sortOrder: 50,
  },
  {
    key: "bp_owner_people",
    label: "People",
    href: "/bp-owner/people",
    icon: "people",
    visibility: "default",
    defaultRoles: ["BP_OWNER"],
    exposeWhenPermissions: ["bp_owner_access", "people_access"],
    sortOrder: 60,
  },
  {
    key: "bp_owner_onboarding",
    label: "Onboarding",
    href: "/bp-owner/onboarding",
    icon: "field_log",
    visibility: "default",
    defaultRoles: ["BP_OWNER"],
    exposeWhenPermissions: ["bp_owner_access"],
    sortOrder: 70,
  },
  {
    key: "bp_owner_metrics",
    label: "Metrics",
    href: "/bp-owner/metrics",
    icon: "chart",
    visibility: "default",
    defaultRoles: ["BP_OWNER"],
    exposeWhenPermissions: ["bp_owner_access", "metrics_access"],
    sortOrder: 80,
  },


  {
    key: "company_manager_metrics",
    label: "Metrics",
    href: "/company-manager/metrics",
    icon: "chart",
    visibility: "default",
    defaultRoles: ["COMPANY_MANAGER"],
    exposeWhenPermissions: ["metrics_access"],
    sortOrder: 90,
  },
  {
    key: "company_manager_workforce",
    label: "Workforce",
    href: "/company-manager/workforce",
    icon: "workforce",
    visibility: "default",
    defaultRoles: ["COMPANY_MANAGER"],
    exposeWhenPermissions: ["workforce_access"],
    sortOrder: 100,
  },
  {
    key: "company_manager_people",
    label: "People",
    href: "/company-manager/people",
    icon: "people",
    visibility: "default",
    defaultRoles: ["COMPANY_MANAGER"],
    exposeWhenPermissions: ["people_access"],
    sortOrder: 110,
  },

  {
    key: "company_supervisor_metrics",
    label: "Metrics",
    href: "/company-supervisor/metrics",
    icon: "chart",
    visibility: "default",
    defaultRoles: ["ITG_SUPERVISOR"],
    exposeWhenPermissions: ["metrics_access"],
    sortOrder: 120,
  },
  {
    key: "company_supervisor_workforce",
    label: "Workforce",
    href: "/company-supervisor/workforce",
    icon: "workforce",
    visibility: "default",
    defaultRoles: ["ITG_SUPERVISOR"],
    exposeWhenPermissions: ["workforce_access"],
    sortOrder: 130,
  },
  {
    key: "company_supervisor_people",
    label: "People",
    href: "/company-supervisor/people",
    icon: "people",
    visibility: "default",
    defaultRoles: ["ITG_SUPERVISOR"],
    exposeWhenPermissions: ["people_access"],
    sortOrder: 140,
  },

  {
    key: "bp_lead_overview",
    label: "Overview",
    href: "/bp-lead",
    icon: "home",
    visibility: "default",
    defaultRoles: ["BP_LEAD"],
    sortOrder: 145,
  },
  {
    key: "bp_lead_workforce",
    label: "Workforce",
    href: "/bp-lead/workforce",
    icon: "workforce",
    visibility: "default",
    defaultRoles: ["BP_LEAD"],
    sortOrder: 146,
  },
  {
    key: "bp_lead_people",
    label: "People",
    href: "/bp-lead/people",
    icon: "people",
    visibility: "default",
    defaultRoles: ["BP_LEAD"],
    sortOrder: 147,
  },
  {
    key: "bp_lead_onboarding",
    label: "Onboarding",
    href: "/bp-lead/onboarding",
    icon: "field_log",
    visibility: "default",
    defaultRoles: ["BP_LEAD"],
    sortOrder: 148,
  },
  {
    key: "bp_lead_metrics",
    label: "Metrics",
    href: "/bp-lead/metrics",
    icon: "chart",
    visibility: "default",
    defaultRoles: ["BP_LEAD"],
    sortOrder: 149,
  },

  {
    key: "bp_supervisor_overview",
    label: "Home",
    href: "/bp-supervisor",
    icon: "home",
    visibility: "default",
    defaultRoles: ["BP_SUPERVISOR"],
    sortOrder: 149,
  },

  {
    key: "bp_supervisor_metrics",
    label: "Metrics",
    href: "/bp-supervisor/metrics",
    icon: "chart",
    visibility: "default",
    defaultRoles: ["BP_SUPERVISOR"],
    exposeWhenPermissions: ["metrics_access"],
    sortOrder: 150,
  },


  {
    key: "tech_home",
    label: "Home",
    href: "/tech",
    icon: "home",
    visibility: "default",
    defaultRoles: ["TECH"],
    sortOrder: 200,
  },
  {
    key: "tech_schedule",
    label: "Schedule",
    href: "/tech/schedule",
    icon: "calendar",
    visibility: "default",
    defaultRoles: ["TECH"],
    sortOrder: 210,
  },
  {
    key: "tech_metrics",
    label: "Metrics",
    href: "/tech/metrics",
    icon: "chart",
    visibility: "default",
    defaultRoles: ["TECH"],
    sortOrder: 220,
  },
  {
    key: "tech_field_log",
    label: "Field Log",
    href: "/tech/field-log",
    icon: "field_log",
    visibility: "default",
    defaultRoles: ["TECH"],
    sortOrder: 230,
  },

  {
    key: "field_log",
    label: "Field Log",
    href: "/field-log",
    icon: "field_log",
    visibility: "default",
    defaultRoles: [
      "APP_OWNER",
      "ADMIN",
      "DIRECTOR",
      "ITG_SUPERVISOR",
      "COMPANY_MANAGER",
      "BP_SUPERVISOR",
      "BP_LEAD",
      "BP_OWNER",
    ],
    exposeWhenPermissions: ["field_log_access"],
    sortOrder: 300,
  },
  {
    key: "booking",
    label: "Booking",
    href: "/schedule",
    icon: "calendar",
    visibility: "default",
    defaultRoles: [
      "APP_OWNER",
      "ADMIN",
      "DIRECTOR",
      "ITG_SUPERVISOR",
      "COMPANY_MANAGER",
      "BP_SUPERVISOR",
      "BP_LEAD",
      "BP_OWNER",
    ],
    exposeWhenPermissions: [
      "route_lock_access",
      "route_lock_read",
      "route_lock_manage",
      "dispatch_console_access",
      "dispatch_manage",
      "workforce_access",
    ],
    sortOrder: 305,
  },

  {
    key: "route_lock",
    label: "Route Lock",
    href: "/route-lock",
    icon: "route_lock",
    visibility: "grant",
    exposeWhenPermissions: [
      "route_lock_access",
      "route_lock_read",
      "route_lock_manage",
    ],
    sortOrder: 310,
  },
  {
    key: "dispatch_console",
    label: "Dispatch Console",
    href: "/dispatch-console",
    icon: "clipboard",
    visibility: "default",
    defaultRoles: [
      "ITG_SUPERVISOR",
      "COMPANY_MANAGER",
      "BP_SUPERVISOR",
      "BP_LEAD",
      "BP_OWNER",
    ],
    exposeWhenPermissions: ["dispatch_console_access", "dispatch_manage"],
    sortOrder: 320,
  },
  {
    key: "metrics_uploads",
    label: "Metrics Uploads",
    href: "/metrics/uploads",
    icon: "chart",
    visibility: "grant",
    exposeWhenPermissions: ["metrics_uploads", "metrics_manage"],
    sortOrder: 330,
  },

  {
    key: "admin",
    label: "Admin",
    href: "/admin",
    icon: "admin",
    visibility: "default",
    defaultRoles: ["APP_OWNER", "ADMIN"],
    exposeWhenPermissions: ["admin_access"],
    sortOrder: 900,
  },
];

export const ACCOUNT_NAVIGATION_ITEMS: NavigationItemDefinition[] = [
  {
    key: "profile",
    label: "Profile",
    href: "/profile",
    icon: "profile",
    visibility: "default",
    defaultRoles: [
      "APP_OWNER",
      "ADMIN",
      "DIRECTOR",
      "TECH",
      "ITG_SUPERVISOR",
      "COMPANY_MANAGER",
      "BP_SUPERVISOR",
      "BP_LEAD",
      "BP_OWNER",
      "UNSCOPED",
      "UNKNOWN",
    ],
    sortOrder: 10,
  },
];