// path: apps/web/src/shared/navigation/registry.ts

import type { NavigationItemDefinition } from "./types";

export const NAVIGATION_REGISTRY: NavigationItemDefinition[] = [
  {
    key: "home",
    label: "Home",
    href: "/home",
    icon: "home",
    visibility: "default",
    defaultRoles: ["APP_OWNER", "ADMIN", "DIRECTOR", "ITG_SUPERVISOR", "COMPANY_MANAGER"],
    sortOrder: 10,
  },
  {
    key: "director_executive",
    label: "Director Executive Snapshot",
    href: "/director/executive",
    icon: "chart",
    visibility: "default",
    defaultRoles: ["APP_OWNER", "ADMIN", "DIRECTOR"],
    sortOrder: 20,
  },

  {
    key: "bp_owner_overview",
    label: "Overview",
    href: "/bp-owner",
    icon: "home",
    visibility: "default",
    defaultRoles: ["BP_OWNER"],
    exposeWhenPermissions: ["bp_owner_access"],
    sortOrder: 30,
  },
  {
    key: "bp_owner_workforce",
    label: "Workforce",
    href: "/bp-owner/workforce",
    icon: "workforce",
    visibility: "default",
    defaultRoles: ["BP_OWNER"],
    exposeWhenPermissions: ["bp_owner_access", "workforce_access"],
    sortOrder: 40,
  },
  {
    key: "bp_owner_people",
    label: "People",
    href: "/bp-owner/people",
    icon: "people",
    visibility: "default",
    defaultRoles: ["BP_OWNER"],
    exposeWhenPermissions: ["bp_owner_access", "people_access"],
    sortOrder: 50,
  },
  {
    key: "bp_owner_metrics",
    label: "Metrics",
    href: "/bp-owner/metrics",
    icon: "chart",
    visibility: "default",
    defaultRoles: ["BP_OWNER"],
    exposeWhenPermissions: ["bp_owner_access", "metrics_access"],
    sortOrder: 60,
  },

  {
    key: "company_supervisor",
    label: "Company Supervisor",
    href: "/company-supervisor",
    icon: "workforce",
    visibility: "default",
    defaultRoles: ["APP_OWNER", "ADMIN", "ITG_SUPERVISOR"],
    sortOrder: 80,
  },
  {
    key: "company_manager",
    label: "Company Manager",
    href: "/company-manager",
    icon: "workforce",
    visibility: "default",
    defaultRoles: ["APP_OWNER", "ADMIN", "COMPANY_MANAGER"],
    sortOrder: 90,
  },
  {
    key: "bp_supervisor_metrics",
    label: "Metrics",
    href: "/bp-supervisor/metrics",
    icon: "chart",
    visibility: "default",
    defaultRoles: ["BP_SUPERVISOR", "BP_LEAD"],
    exposeWhenPermissions: ["metrics_access"],
    sortOrder: 100,
  },

  {
    key: "metrics_uploads",
    label: "Metrics Uploads",
    href: "/metrics/uploads",
    icon: "chart",
    visibility: "grant",
    exposeWhenPermissions: ["metrics_uploads", "metrics_manage"],
    sortOrder: 110,
  },
  {
    key: "route_lock",
    label: "Route Lock",
    href: "/route-lock",
    icon: "route_lock",
    visibility: "grant",
    exposeWhenPermissions: ["route_lock_access", "route_lock_read", "route_lock_manage"],
    sortOrder: 120,
  },
  {
    key: "dispatch_console",
    label: "Dispatch Console",
    href: "/dispatch-console",
    icon: "clipboard",
    visibility: "grant",
    defaultRoles: ["APP_OWNER", "ADMIN"],
    exposeWhenPermissions: ["dispatch_console_access", "dispatch_manage"],
    sortOrder: 130,
  },
  {
    key: "field_log",
    label: "Field Log",
    href: "/field-log",
    icon: "field_log",
    visibility: "default",
    defaultRoles: ["APP_OWNER", "ADMIN", "ITG_SUPERVISOR", "COMPANY_MANAGER", "BP_SUPERVISOR", "BP_LEAD"],
    exposeWhenPermissions: ["field_log_access"],
    sortOrder: 140,
  },

  {
    key: "roster",
    label: "Roster",
    href: "/roster",
    icon: "people",
    visibility: "default",
    defaultRoles: ["APP_OWNER", "ADMIN"],
    exposeWhenPermissions: ["roster_manage"],
    sortOrder: 150,
  },
  {
    key: "people",
    label: "People",
    href: "/people",
    icon: "people",
    visibility: "default",
    defaultRoles: ["APP_OWNER", "ADMIN", "ITG_SUPERVISOR", "COMPANY_MANAGER"],
    exposeWhenPermissions: ["people_access"],
    sortOrder: 160,
  },
  {
    key: "workforce",
    label: "Workforce",
    href: "/workforce",
    icon: "workforce",
    visibility: "default",
    defaultRoles: ["APP_OWNER", "ADMIN", "ITG_SUPERVISOR", "COMPANY_MANAGER"],
    exposeWhenPermissions: ["workforce_access"],
    sortOrder: 170,
  },
  {
    key: "admin",
    label: "Admin",
    href: "/admin",
    icon: "admin",
    visibility: "default",
    defaultRoles: ["APP_OWNER", "ADMIN"],
    exposeWhenPermissions: ["admin_access"],
    sortOrder: 900,
  },
];

export const ACCOUNT_NAVIGATION_ITEMS: NavigationItemDefinition[] = [
  {
    key: "profile",
    label: "Profile",
    href: "/profile",
    icon: "profile",
    visibility: "default",
    defaultRoles: [
      "APP_OWNER",
      "ADMIN",
      "DIRECTOR",
      "TECH",
      "ITG_SUPERVISOR",
      "COMPANY_MANAGER",
      "BP_SUPERVISOR",
      "BP_LEAD",
      "BP_OWNER",
      "UNSCOPED",
      "UNKNOWN",
    ],
    sortOrder: 10,
  },
];