"use client";
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { Card } from "@/components/ui/Card";

type Row = { record_id:string; source_as_of_at:string|null; unique_tickets:number; overdue:number; due_within_4_hours:number; without_response_evidence:number; duplicate_ticket_ids:number; created_at:string };
export function MassachusettsSlaExposureHistoryClient() {
  const [rows,setRows]=useState<Row[]>([]); const [err,setErr]=useState<string|null>(null); const [loading,setLoading]=useState(false);
  const load=useCallback(async()=>{setLoading(true);setErr(null);try{const r=await fetch('/api/locate/reporting-helper/history?report_type=MASSACHUSETTS_SLA_EXPOSURE&pageIndex=0&pageSize=100');const j=await r.json();if(!r.ok)throw new Error(j.error??'Failed to load history');setRows(j.rows??[])}catch(e:any){setErr(e?.message??'Failed to load history')}finally{setLoading(false)}},[]);
  useEffect(()=>{void load()},[load]);
  return <div className="grid gap-4">{err?<Card><div className="text-sm text-[var(--to-danger)]">{err}</div></Card>:null}<Card><div className="mb-3 flex justify-end"><Link href="/locate/reporting-helper?reportType=MASSACHUSETTS_SLA_EXPOSURE" className="to-btn rounded border px-3 py-2 text-sm" style={{borderColor:'var(--to-border)'}}>New snapshot</Link></div><div className="overflow-auto rounded border" style={{borderColor:'var(--to-border)'}}><table className="w-full text-sm"><thead className="bg-[var(--to-surface-2)]"><tr className="text-left"><th className="px-3 py-2">As of</th><th className="px-3 py-2">Tickets</th><th className="px-3 py-2">Overdue</th><th className="px-3 py-2">Due ≤4h</th><th className="px-3 py-2">No response</th><th className="px-3 py-2">Duplicates</th><th className="px-3 py-2 text-right">Open</th></tr></thead><tbody>{rows.length?rows.map(row=><tr key={row.record_id} className="border-t" style={{borderColor:'var(--to-border)'}}><td className="px-3 py-2 whitespace-nowrap">{row.source_as_of_at?new Date(row.source_as_of_at).toLocaleString():'—'}</td><td className="px-3 py-2">{row.unique_tickets}</td><td className="px-3 py-2 font-semibold">{row.overdue}</td><td className="px-3 py-2">{row.due_within_4_hours}</td><td className="px-3 py-2">{row.without_response_evidence}</td><td className="px-3 py-2">{row.duplicate_ticket_ids}</td><td className="px-3 py-2 text-right"><Link href={`/locate/reporting-helper/reports/${row.record_id}`} className="to-btn rounded border px-2 py-1 text-xs" style={{borderColor:'var(--to-border)'}}>Open</Link></td></tr>):<tr><td colSpan={7} className="px-3 py-8 text-center text-[var(--to-ink-muted)]">{loading?'Loading…':'No saved Massachusetts SLA snapshots yet.'}</td></tr>}</tbody></table></div></Card></div>;
}
